apiVersion: v1
kind: Service
metadata:
  name: fare-model-service
  namespace: pyconlt
spec:
  selector:
    app: fare-model
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: fare-model-service-nodeport
  namespace: pyconlt
spec:
  type: LoadBalancer
  selector:
    app: fare-model
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8086
    targetPort: 80