apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-model-deployment
  labels:
    app: time-model
  namespace: pyconlt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-model
  template:
    metadata:
      labels:
        app: time-model
    spec:
      containers:
      - name: time-model
        image: time-predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80